In [1]:
from mysql.connector import(connection)
import random
from datetime import date,timedelta

conn=connection.MySQLConnection(user='root',password='arachana',
                                host='127.0.0.1',database='banking_mang')
if conn.is_connected():
    print('conn connected')
cursor=conn.cursor()
c=True
try:
    #q1='CREATE TABLE banker_info (banker_name varchar(30),banker_email varchar(20),banker_id varchar(15));'
    q2='CREATE TABLE branch (branch_id varchar(16),branch_name varchar(30),branch_city varchar(20),branch_asset varchar(100),PRIMARY KEY(branch_id));'
    q3='CREATE TABLE customer (branch_id varchar(16),cus_id integer(10),cus_name varchar(20),cus_dob varchar(12),cus_email varchar(20),cus_gender varchar(7), PRIMARY KEY(cus_id));'
    q4='CREATE TABLE account (acc_no varchar(10) ,branch_id varchar(16),cus_id integer(10),acc_balance varchar(100),PRIMARY KEY(acc_no));'
    q5='CREATE TABLE deposit (branch_id varchar(16),cus_id integer(10),acc_no varchar(10),deposit_amount varchar(100),deposit_date varchar(10));'
    q6='CREATE TABLE debit (branch_id varchar(16),cus_id integer(10),acc_no varchar(10),debit_amount varchar(100),debit_date varchar(10));'
    q7='CREATE TABLE loan (branch_id varchar(16),cus_id integer(10),loan_amount varchar(100),loan_due_data varchar(10));' 
   
    #cursor.execute(q1)
    cursor.execute(q2)
    cursor.execute(q3)
    cursor.execute(q4)
    cursor.execute(q5)
    cursor.execute(q6)
    cursor.execute(q7)
    
    q8='ALTER TABLE customer ADD FOREIGN KEY (branch_id) REFERENCES branch (branch_id);'
    q9='ALTER TABLE `deposit` ADD FOREIGN KEY (`branch_id`) REFERENCES `customer` (`branch_id`);'
    q10='ALTER TABLE `deposit` ADD FOREIGN KEY (`cus_id`) REFERENCES `customer` (`cus_id`);'
    q11='ALTER TABLE `account` ADD FOREIGN KEY (`branch_id`) REFERENCES `customer` (`branch_id`);'
    q12='ALTER TABLE `account` ADD FOREIGN KEY (`cus_id`) REFERENCES `customer` (`cus_id`);'
    q13='ALTER TABLE `deposit` ADD FOREIGN KEY (`acc_no`) REFERENCES `account` (`acc_no`);'
    q14='ALTER TABLE `debit` ADD FOREIGN KEY (`branch_id`) REFERENCES `customer` (`branch_id`);'
    q15='ALTER TABLE `debit` ADD FOREIGN KEY (`cus_id`) REFERENCES `customer` (`cus_id`);'
    q16='ALTER TABLE `debit` ADD FOREIGN KEY (`acc_no`) REFERENCES `account` (`acc_no`);'
    q17='ALTER TABLE `loan` ADD FOREIGN KEY (`branch_id`) REFERENCES `customer` (`branch_id`);'
    q18='ALTER TABLE `loan` ADD FOREIGN KEY (`cus_id`) REFERENCES `customer` (`cus_id`);'
    
    cursor.execute(q8)
    cursor.execute(q9)
    cursor.execute(q10)
    cursor.execute(q11)
    cursor.execute(q12)
    cursor.execute(q13)
    cursor.execute(q14)
    cursor.execute(q15)
    cursor.execute(q16)
    cursor.execute(q17)
    cursor.execute(q18)
      

    q19='insert into branch (branch_id,branch_name,branch_city,branch_asset) values (%s,%s,%s,%s);'
    t=('kvb2021','kvb','salem',100000000)
    cursor.execute(q19,t)
    print("----Weclome to KVB bank----")
    print("-------Bank Details--------")
    qn='select * from branch'
    cursor.execute(qn)
    for i in cursor:
        print(i)
    while c:
        
        print("1-CREATE ACCOUNT")
        print("2-DEPOSIT")
        print("3-DEBIT")
        print("4-LOAN")
        print("5-DELETE ACCOUNT")
        print("6-EXIT")
        
        n=int(input("enter your choice"))
        c1=True
        if(n==1):
            
            while c1:
                x1=input("Enter the branch_Id -- ")
                q20= 'select * from branch;'
                cursor.execute(q20)
                for i in cursor:
                    a=i[0]
                    
                if(x1==a):
                    x2=input("Enter your name")
                    x3=input("Enter your Date of birth --dd/mm/yr--")
                    x4=input("Enter your email") 
                    x5=input("Enter your Gender --male/female")
                    x6=random.randint(11111,99999)
                    x7=random.randint(100000000,9999999999)
                    x8=0
                    q21='insert into customer(branch_id,cus_id,cus_name,cus_dob,cus_email,cus_gender)values (%s,%s,%s,%s,%s,%s);'
                    q22='insert into account(acc_no,branch_id,cus_id,acc_balance) values (%s,%s,%s,%s);'
                    q23='insert into deposit (branch_id,cus_id,acc_no,deposit_amount)values (%s,%s,%s,%s);'
                    q24='insert into debit (branch_id,cus_id,acc_no,debit_amount) values (%s,%s,%s,%s);'
                    q25='insert into loan (branch_id,cus_id,loan_amount) values (%s,%s,%s)'
                    t1=(a,x6,x2,x3,x4,x5)
                    t2=(x7,a,x6,x8)
                    t3=(a,x6,x7,x8)
                    t4=(a,x6,x7,x8)
                    t5=(a,x6,x8)
                    cursor.execute(q21,t1)
                    cursor.execute(q22,t2)
                    cursor.execute(q23,t3)
                    cursor.execute(q24,t4)
                    cursor.execute(q25,t5)
                    print("Your's Customer Id id -- ",x6)
                    c1=False
                else:
                    print("Enter valid Branch-Id")
                    c1=True
        
        elif(n==2):
            print("-------welcome to KVB Deposit Section---------- ")
            x1=input("Enter your Customer-ID for further Steps -- ")
            q26='select * from deposit where cus_id=%s;'
            t6=(x1,)
            cursor.execute(q26,t6)
            x2=int(input("Enter the amount to be deposited -- "))
            for i in cursor:
                print(i[3])
                x3=int(i[3])+x2
                x4=i[2]
            #print(type(x3))
            date=date.today()
            q27='update deposit set deposit_amount=%s,deposit_date=%s where cus_id=%s;'
            q28='update account set acc_balance=%s where cus_id=%s;'
            t7=(x2,date,x1)
            t8=(x3,x1)
            cursor.execute(q27,t7)
            cursor.execute(q28,t8)
            print("----------thank you your amount have been Deposited---------")
            
        elif(n==3):
            print("-------welcome to KVB Debit Section---------- ")
            x1=input("Enter your Customer-ID for further Steps -- ")
            q29='select * from account where cus_id=%s;'
            t9=(x1,)
            cursor.execute(q29,t9)
            x2=int(input("Enter the amount to be debited from your account -- "))
            for i in cursor:
                x3=int(i[3])-x2
            #print(type(x3))
            date=date.today()
            q30='update debit set debit_amount=%s,debit_date=%s where cus_id=%s;'
            q31='update account set acc_balance=%s where cus_id=%s;'
            t10=(x2,date,x1)
            t11=(x3,x1)
            cursor.execute(q30,t10)
            cursor.execute(q31,t11)
            print("----------thank you your amount have been Debit section---------")
        
        elif(n==4):
            print("------------------welcome to Kvb Load section----------------------")
            x1=input("Enter your Customer-ID for further Steps -- ")
            #q32='select * from loan where cus_id=%s;'
            #t12=(x1,)
            #cursor.execute(q32,t12)
            x2=int(input("Enter your Monthly Salary Amount"))
            x3=x2*5
            year=timedelta(days=365)
            print("your eligible for ",x3," Rupees Loan")
            x4=input("If you are willing to access it --- Enter  'y' or not intrested enter 'n'")
            if x4=='y':
                q33='select * from account where cus_id=%s;'
                t13=(x1,)
                cursor.execute(q33,t13)
                for i in cursor:
                    x5=int(i[3])+x3
                date=date.today()
                five_yr=5*year
                finalday=date+five_yr
                q34='update account set acc_balance=%s where cus_id=%s;'
                q35='update loan set loan_amount=%s where cus_id=%s;'
                t14=(x5,x1)
                t15=(x3,x1)
                cursor.execute(q34,t14)
                cursor.execute(q35,t15)
                print("-------------------loan amount has be credited to your account--------------------")
                print("------------------------thanks for getting loan in KVB----------------------------")
            elif x4=='n':
                print("----------------you are not intrested to get loan Thank you--------------------")
        
        elif(n==5):
            print("----------welcome to delete account section---------------")
            x1=input("Enter your Customer-ID for further Steps -- ")
            q36='delete from loan where cus_id=%s;' 
            q37='delete from debit where cus_id=%s;'
            q38='delete from deposit where cus_id=%s;'
            q39='delete from account where cus_id=%s;'
            q40='delete from customer where cus_id=%s;'
            t16=(x1,)
            cursor.execute(q36,t16)
            #print("w1")
            cursor.execute(q37,t16)
            #print("w2")
            cursor.execute(q39,t16)
            #print("w3")
            cursor.execute(q38,t16)
            #print("w4")
            cursor.execute(q40,t16)
            
            
        elif(n==6):
            c=False
            
except Exception as e:
    print('===== following exception is raised======')
    print(e)
finally:
    pass
conn.commit()
conn.close()
print('PROJECT EXECUTED SUCCESSFULLY')

conn connected
----Weclome to KVB bank----
-------Bank Details--------
('kvb2021', 'kvb', 'salem', '100000000')
1-CREATE ACCOUNT
2-DEPOSIT
3-DEBIT
4-LOAN
5-DELETE ACCOUNT
6-EXIT
enter your choice1
Enter the branch_Id -- kvb2021
Enter your namearchana
Enter your Date of birth --dd/mm/yr--19-03-2002
Enter your emailarchana@kongu.edu
Enter your Gender --male/femalefemale
Your's Customer Id id --  30176
1-CREATE ACCOUNT
2-DEPOSIT
3-DEBIT
4-LOAN
5-DELETE ACCOUNT
6-EXIT
enter your choice1
Enter the branch_Id -- kvb2021
Enter your nameboomika
Enter your Date of birth --dd/mm/yr--10/10/2001
Enter your emailboomi@gmail.com
Enter your Gender --male/femalefemale
Your's Customer Id id --  54041
1-CREATE ACCOUNT
2-DEPOSIT
3-DEBIT
4-LOAN
5-DELETE ACCOUNT
6-EXIT
enter your choice3
-------welcome to KVB Debit Section----------
Enter your Customer-ID for further Steps -- 54041
Enter the amount to be debited from your account -- 1000
----------thank you your amount have been Debit section---------
1-CREATE ACCOUNT
2-DEPOSIT
3-DEBIT
4-LOAN
5-DELETE ACCOUNT
6-EXIT
enter your choice4
------------------welcome to Kvb Load section----------------------
Enter your Customer-ID for further Steps -- 30176
Enter your Monthly Salary Amount5000
your eligible for  25000  Rupees Loan
If you are willing to access it --- Enter  'y' or not intrested enter 'n'y
-------------------loan amount has be credited to your account--------------------
------------------------thanks for getting loan in KVB----------------------------
1-CREATE ACCOUNT
2-DEPOSIT
3-DEBIT
4-LOAN
5-DELETE ACCOUNT
6-EXIT
enter your choice6
PROJECT EXECUTED SUCCESSFULLY